### ISSUE TITLE
sh: 1: cross-env: not found

### ISSUE THREAD

**Issue by vladimirmyshkovski** [vchaptsev/cookiecutter-django-vue#1]
Hello.

If I try run `docker-compose up`, I get error with this traceback:

```
webpack_1   | sh: 1: cross-env: not found
webpack_1   | npm ERR! file sh
webpack_1   | npm ERR! code ELIFECYCLE
webpack_1   | npm ERR! errno ENOENT
webpack_1   | npm ERR! syscall spawn
webpack_1   | npm ERR! vuetest@0.0.1 dev: `cross-env NODE_ENV=development webpack-dev-server`
webpack_1   | npm ERR! spawn ENOENT
webpack_1   | npm ERR! 
webpack_1   | npm ERR! Failed at the vuetest@0.0.1 dev script.
webpack_1   | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
webpack_1   | npm WARN Local package.json exists, but node_modules missing, did you mean to install?
webpack_1   | 
webpack_1   | npm ERR! A complete log of this run can be found in:
webpack_1   | npm ERR!     /root/.npm/_logs/2017-10-30T20_53_34_207Z-debug.log
webpack_1   | 
webpack_1   | > vuetest@0.0.1 dev /app
webpack_1   | > cross-env NODE_ENV=development webpack-dev-server
webpack_1   | 
webpack_1   | Project is running at http://0.0.0.0:3000/
webpack_1   | webpack output is served from http://localhost:3000/static/dist/
webpack_1   | 404s will fallback to /index.html
webpack_1   | Hash: 568828082515fca998b7
webpack_1   | Version: webpack 2.7.0
webpack_1   | Time: 3730ms
webpack_1   | chunk    {0} build.js (main) 810 kB [entry] [rendered]
webpack_1   |     [3] ./~/vue/dist/vue.esm.js 282 kB {0} [built]
webpack_1   |     [4] ./~/axios/index.js 40 bytes {0} [built]
webpack_1   |    [14] (webpack)/hot/emitter.js 77 bytes {0} [built]
webpack_1   |    [15] ./vuetest/static/main.js 1.05 kB {0} [built]
webpack_1   |    [16] (webpack)-dev-server/client?http://0.0.0.0:3000 7.95 kB {0} [built]
webpack_1   |    [17] (webpack)/hot/dev-server.js 1.57 kB {0} [built]
webpack_1   |    [56] ./~/url/url.js 23.3 kB {0} [built]
webpack_1   |    [58] ./vuetest/static/Main.vue 1.75 kB {0} [built]
webpack_1   |    [61] ./~/vue-meta/lib/vue-meta.js 33.1 kB {0} [built]
webpack_1   |    [62] ./~/vue-progressbar/dist/vue-progressbar.js 6.23 kB {0} [built]
webpack_1   |    [68] (webpack)-dev-server/client/overlay.js 3.73 kB {0} [built]
webpack_1   |    [69] (webpack)-dev-server/client/socket.js 1.05 kB {0} [built]
webpack_1   |    [71] (webpack)/hot nonrecursive ^\.\/log$ 160 bytes {0} [built]
webpack_1   |    [72] (webpack)/hot/log-apply-result.js 1.02 kB {0} [built]
webpack_1   |    [73] multi (webpack)-dev-server/client?http://0.0.0.0:3000 webpack/hot/dev-server ./vuetest/static/main.js 52 bytes {0} [built]
webpack_1   |      + 59 hidden modules
webpack_1   | 
webpack_1   | ERROR in ./~/css-loader!./~/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-111a39d7","scoped":false,"hasInlineConfig":false}!./~/sass-loader/lib/loader.js!./~/vue-loader/lib/selector.js?type=styles&index=0!./vuetest/static/Main.vue
webpack_1   | Module build failed: Error: Missing binding /app/node_modules/node-sass/vendor/linux-x64-57/binding.node
webpack_1   | Node Sass could not find a binding for your current environment: Linux 64-bit with Node.js 8.x
webpack_1   | 
webpack_1   | Found bindings for the following environments:
webpack_1   |   - Linux 64-bit with Node.js 6.x
webpack_1   | 
webpack_1   | This usually happens because your environment has changed since running `npm install`.
webpack_1   | Run `npm rebuild node-sass --force` to build the binding for your current environment.
webpack_1   |     at module.exports (/app/node_modules/node-sass/lib/binding.js:15:13)
webpack_1   |     at Object.<anonymous> (/app/node_modules/node-sass/lib/index.js:14:35)
webpack_1   |     at Module._compile (module.js:612:30)
webpack_1   |     at Object.Module._extensions..js (module.js:623:10)
webpack_1   |     at Module.load (module.js:531:32)
webpack_1   |     at tryModuleLoad (module.js:494:12)
webpack_1   |     at Function.Module._load (module.js:486:3)
webpack_1   |     at Module.require (module.js:556:17)
webpack_1   |     at require (internal/module.js:11:18)
webpack_1   |     at Object.<anonymous> (/app/node_modules/sass-loader/lib/loader.js:3:14)
webpack_1   |  @ ./~/vue-style-loader!./~/css-loader!./~/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-111a39d7","scoped":false,"hasInlineConfig":false}!./~/sass-loader/lib/loader.js!./~/vue-loader/lib/selector.js?type=styles&index=0!./vuetest/static/Main.vue 4:14-330 13:3-17:5 14:22-338
webpack_1   |  @ ./vuetest/static/Main.vue
webpack_1   |  @ ./vuetest/static/main.js
webpack_1   |  @ multi (webpack)-dev-server/client?http://0.0.0.0:3000 webpack/hot/dev-server ./vuetest/static/main.js
webpack_1   | 
webpack_1   | > vuetest@0.0.1 dev /app
webpack_1   | > cross-env NODE_ENV=development webpack-dev-server
webpack_1   | 

```

**Comment by vchaptsev** [comment]
Hello!
Yeah, I can reproduce this bug. 
Temporary workaround: manually run yarn\npm install, then build
`docker-compose run webpack yarn`
`docker-compose up --build`

**Comment by vchaptsev** [comment]
Fixed now, please update
