### ISSUE TITLE
Windows 10 support ?

### ISSUE THREAD

**Issue by guilty80100** [vchaptsev/cookiecutter-django-vue#31]
Hi,

I'm trying to use your project on windows 10.

I had to change CRLF to LF in .sh for the backend to work in docker but that was not a problem to find out.

But the big one I can't figure out is the front end doesn't work. When installing packages I have this error 

```
frontend_1  | > yorkie@2.0.0 install /app/node_modules/yorkie
frontend_1  | > node bin/install.js
frontend_1  |
frontend_1  | fs.js:115
frontend_1  |     throw err;
frontend_1  |     ^
frontend_1  |
frontend_1  | Error: EINVAL: invalid argument, open '/app/node_modules/yorkie/package.json'
frontend_1  |     at Object.openSync (fs.js:439:3)
frontend_1  |     at Object.readFileSync (fs.js:344:35)
frontend_1  |     at Object.Module._extensions..json (internal/modules/cjs/loader.js:706:20)
frontend_1  |     at Module.load (internal/modules/cjs/loader.js:599:32)
frontend_1  |     at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
frontend_1  |     at Function.Module._load (internal/modules/cjs/loader.js:530:3)
frontend_1  |     at Module.require (internal/modules/cjs/loader.js:637:17)
frontend_1  |     at require (internal/modules/cjs/helpers.js:22:18)
frontend_1  |     at Object.<anonymous> (/app/node_modules/yorkie/src/utils/get-hook-script.js:5:13)
frontend_1  |     at Module._compile (internal/modules/cjs/loader.js:689:30)
frontend_1  | npm WARN rollback Rolling back get-stream@3.0.0 failed (this is probably harmless): ENOTEMPTY: directory not empty, rmdir '/app/node_modules/yorkie/node_modules/get-stream'
frontend_1  | npm WARN rollback Rolling back normalize-path@1.0.0 failed (this is probably harmless): ENOTEMPTY: directory not empty, rmdir '/app/node_modules/yorkie/node_modules/normalize-path'
frontend_1  | npm WARN rollback Rolling back lru-cache@4.1.5 failed (this is probably harmless): ENOTEMPTY: directory not empty, rmdir '/app/node_modules/yorkie/node_modules/lru-cache'
frontend_1  | npm WARN rollback Rolling back yallist@2.1.2 failed (this is probably harmless): ENOTEMPTY: directory not empty, rmdir '/app/node_modules/yorkie/node_modules/yallist'
frontend_1  | npm WARN rollback Rolling back strip-indent@2.0.0 failed (this is probably harmless): ENOTEMPTY: directory not empty, rmdir '/app/node_modules/strip-indent'
frontend_1  | npm WARN rollback Rolling back execa@0.8.0 failed (this is probably harmless): ENOTEMPTY: directory not empty, rmdir '/app/node_modules/yorkie/node_modules/execa'
frontend_1  | npm WARN rollback Rolling back cross-spawn@5.1.0 failed (this is probably harmless): ENOTEMPTY: directory not empty, rmdir '/app/node_modules/yorkie/node_modules/cross-spawn'
frontend_1  | npm WARN rollback Rolling back yorkie@2.0.0 failed (this is probably harmless): ENOTEMPTY: directory not empty, rmdir '/app/node_modules/yorkie/node_modules/cross-spawn'
frontend_1  | npm WARN rollback Rolling back @vue/cli-service@3.4.1 failed (this is probably harmless): ENOTEMPTY: directory not empty, rmdir '/app/node_modules/@vue/cli-service/node_modules/debug'
frontend_1  | npm WARN eslint-config-standard@12.0.0 requires a peer of eslint@>=5.0.0 but none is installed. You must install peer dependencies yourself.
frontend_1  | npm WARN eslint-config-standard@12.0.0 requires a peer of eslint-plugin-node@>=7.0.0 but none is installed. You must install peer dependencies yourself.
frontend_1  | npm WARN eslint-config-standard@12.0.0 requires a peer of eslint-plugin-promise@>=4.0.0 but none is installed. You must install peer dependencies
yourself.
frontend_1  | npm WARN eslint-config-standard@12.0.0 requires a peer of eslint-plugin-standard@>=4.0.0 but none is installed. You must install peer dependencies yourself.
frontend_1  | npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/fsevents):
frontend_1  | npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
frontend_1  |
frontend_1  | npm ERR! code ELIFECYCLE
frontend_1  | npm ERR! errno 1
frontend_1  | npm ERR! yorkie@2.0.0 install: `node bin/install.js`
frontend_1  | npm ERR! Exit status 1
frontend_1  | npm ERR!
frontend_1  | npm ERR! Failed at the yorkie@2.0.0 install script.
frontend_1  | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
frontend_1  |
frontend_1  | npm ERR! A complete log of this run can be found in:
frontend_1  | npm ERR!     /root/.npm/_logs/2019-02-25T22_25_14_516Z-debug.log
frontend_1  | npm ERR! code ELIFECYCLE
frontend_1  | npm ERR! errno 1
frontend_1  | npm ERR! frontend@0.1.0 serve: `npm i && vue-cli-service serve`
frontend_1  | npm ERR! Exit status 1
frontend_1  | npm ERR!
frontend_1  | npm ERR! Failed at the frontend@0.1.0 serve script.
frontend_1  | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
frontend_1  |
frontend_1  | npm ERR! A complete log of this run can be found in:
frontend_1  | npm ERR!     /root/.npm/_logs/2019-02-25T22_25_15_151Z-debug.log
````

I found few post online about this kind of problem : 
[https://github.com/vuejs/vue-cli/issues/3466](url)
[https://github.com/vuejs/vue-cli/issues/3056](url)

But I don't know how to fix it.

**Comment by vchaptsev** [comment]
Hey!
Looks like the problem is not in the template, but in `yorkie`
